name: owtest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  firebase_ui_auth: ^3.0.1
  cloud_firestore: ^6.0.3
  flutter_map: ^8.2.2
  flutter_map_location_marker: ^10.1.0
  latlong2: ^0.9.1
  google_sign_in: ^6.2.0
  google_fonts: ^6.2.1 # Added google_fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
