name: owtest
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.2.0
  cupertino_icons: ^1.0.8
  firebase_auth: ^6.1.1
  firebase_ui_auth: ^3.0.1
  cloud_firestore: ^6.0.3
  flutter_map: ^8.2.2
  flutter_map_location_marker: ^10.1.0
  latlong2: ^0.9.1
  google_sign_in: ^6.2.0
  google_fonts: ^6.2.1
  intl: ^0.20.2 # Added for date formatting
  pdf: ^3.11.0
  printing: ^5.13.3
  image_picker: ^0.8.7+5
  flutter_image_compress: ^2.4.0
  tflite_flutter: ^0.10.0
  url_launcher: ^6.1.10
  http: ^1.5.0
  flutter_webrtc: ^1.2.1  # Updated WebRTC version (includes Android namespace)
  socket_io_client: ^3.0.1
  google_generative_ai: ^0.4.7
  table_calendar: ^3.1.1
  flutter_dotenv: ^5.1.0
  flutter_stripe: ^12.1.1
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - .env 
